/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */
#include <stdio.h>
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
int kappa = 0;
char B0;
char B4;
char B5;
char B6;
char B7;
char B10;
char B11;
char B12;
char B13;
char B14;
char B15;
char B16;
char B17;
char B18;
char B19;
char B20;
char B21;
char B22;
char B23;
char B24;
long X1;
long X2;
long X3;
long X4;
long X5;
long X6;
int X7;
int X8;
int X9;
long X10;
long X11;
int X12;
int X13;
int X14;
int X15;
int X16;
int X17;
int X18;
int X19;
int X20;
int X21;
int X22;
int X23;
int X24;
char X25;
char X27;
char X26;
char X28;
char X29;
char X30;
char X31;
char X32;
char X33;
char X34;
char X35;
char X36;
char X37;
char X38;
char X39;
char X40;
char X41;
char X42;
char X43;
char X44;
char X45;
char X46;
char X47;
char X48;
char X49;
char X50;
char X51;
char X52;
char X53;
char X54;
char X55;
char X56;
char X57;
char X58;
char X59;
char X60;
char X61;
char X62;
char X63;
char X64;
char X65;
char X66;
char X67;
char X68;
char X69;
char X70;
char X71;
char X72;
char X73;
char X74;
char X75;
char X76;
char X77;
char X78;
char X79;
char X80;
char X81;
char X82;
char X83;
char X84;
char X85;
char X86;
long time;
char stable;
char step;
char X87;
char X88;
char X89;
char X90;
char X91;
char X92;
char X93;
char X94;
char X95;
char X96;
char X97;
char X98;
char X99;
char X100;
char X101;
char X102;
int t;

int main() {

  {
    klee_make_symbolic(&B0, sizeof(char), "B0");
    klee_make_symbolic(&B4, sizeof(char), "B4");
    klee_make_symbolic(&B5, sizeof(char), "B5");
    klee_make_symbolic(&B6, sizeof(char), "B6");
    klee_make_symbolic(&B7, sizeof(char), "B7");
    klee_make_symbolic(&B10, sizeof(char), "B10");
    klee_make_symbolic(&B11, sizeof(char), "B11");
    klee_make_symbolic(&B12, sizeof(char), "B12");
    klee_make_symbolic(&B13, sizeof(char), "B13");
    klee_make_symbolic(&B14, sizeof(char), "B14");
    klee_make_symbolic(&B15, sizeof(char), "B15");
    klee_make_symbolic(&B16, sizeof(char), "B16");
    klee_make_symbolic(&B17, sizeof(char), "B17");
    klee_make_symbolic(&B18, sizeof(char), "B18");
    klee_make_symbolic(&B19, sizeof(char), "B19");
    klee_make_symbolic(&B20, sizeof(char), "B20");
    klee_make_symbolic(&B21, sizeof(char), "B21");
    klee_make_symbolic(&B22, sizeof(char), "B22");
    klee_make_symbolic(&B23, sizeof(char), "B23");
    klee_make_symbolic(&B24, sizeof(char), "B24");
    klee_make_symbolic(&X1, sizeof(long), "X1");
    klee_make_symbolic(&X2, sizeof(long), "X2");
    klee_make_symbolic(&X3, sizeof(long), "X3");
    klee_make_symbolic(&X4, sizeof(long), "X4");
    klee_make_symbolic(&X5, sizeof(long), "X5");
    klee_make_symbolic(&X6, sizeof(long), "X6");
    klee_make_symbolic(&X7, sizeof(int), "X7");
    klee_make_symbolic(&X8, sizeof(int), "X8");
    klee_make_symbolic(&X9, sizeof(int), "X9");
    klee_make_symbolic(&X10, sizeof(long), "X10");
    klee_make_symbolic(&X11, sizeof(long), "X11");
    klee_make_symbolic(&X12, sizeof(int), "X12");
    klee_make_symbolic(&X13, sizeof(int), "X13");
    klee_make_symbolic(&X14, sizeof(int), "X14");
    klee_make_symbolic(&X15, sizeof(int), "X15");
    klee_make_symbolic(&X16, sizeof(int), "X16");
    klee_make_symbolic(&X17, sizeof(int), "X17");
    klee_make_symbolic(&X18, sizeof(int), "X18");
    klee_make_symbolic(&X19, sizeof(int), "X19");
    klee_make_symbolic(&X20, sizeof(int), "X20");
    klee_make_symbolic(&X21, sizeof(int), "X21");
    klee_make_symbolic(&X22, sizeof(int), "X22");
    klee_make_symbolic(&X23, sizeof(int), "X23");
    klee_make_symbolic(&X24, sizeof(int), "X24");
    klee_make_symbolic(&X25, sizeof(char), "X25");
    klee_make_symbolic(&X26, sizeof(char), "X26");
    klee_make_symbolic(&X27, sizeof(char), "X27");
    klee_make_symbolic(&X28, sizeof(char), "X28");
    klee_make_symbolic(&X29, sizeof(char), "X29");
    klee_make_symbolic(&X30, sizeof(char), "X30");
    klee_make_symbolic(&X31, sizeof(char), "X31");
    klee_make_symbolic(&X32, sizeof(char), "X32");
    klee_make_symbolic(&X33, sizeof(char), "X33");
    klee_make_symbolic(&X34, sizeof(char), "X34");
    klee_make_symbolic(&X35, sizeof(char), "X35");
    klee_make_symbolic(&X36, sizeof(char), "X36");
    klee_make_symbolic(&X37, sizeof(char), "X37");
    klee_make_symbolic(&X38, sizeof(char), "X38");
    klee_make_symbolic(&X39, sizeof(char), "X39");
    klee_make_symbolic(&X40, sizeof(char), "X40");
    klee_make_symbolic(&X41, sizeof(char), "X41");
    klee_make_symbolic(&X42, sizeof(char), "X42");
    klee_make_symbolic(&X43, sizeof(char), "X43");
    klee_make_symbolic(&X44, sizeof(char), "X44");
    klee_make_symbolic(&X45, sizeof(char), "X45");
    klee_make_symbolic(&X46, sizeof(char), "X46");
    klee_make_symbolic(&X47, sizeof(char), "X47");
    klee_make_symbolic(&X48, sizeof(char), "X48");
    klee_make_symbolic(&X49, sizeof(char), "X49");
    klee_make_symbolic(&X50, sizeof(char), "X50");
    klee_make_symbolic(&X51, sizeof(char), "X51");
    klee_make_symbolic(&X52, sizeof(char), "X52");
    klee_make_symbolic(&X53, sizeof(char), "X53");
    klee_make_symbolic(&X54, sizeof(char), "X54");
    klee_make_symbolic(&X55, sizeof(char), "X55");
    klee_make_symbolic(&X56, sizeof(char), "X56");
    klee_make_symbolic(&X57, sizeof(char), "X57");
    klee_make_symbolic(&X58, sizeof(char), "X58");
    klee_make_symbolic(&X59, sizeof(char), "X59");
    klee_make_symbolic(&X60, sizeof(char), "X50");
    klee_make_symbolic(&X61, sizeof(char), "X61");
    klee_make_symbolic(&X62, sizeof(char), "X62");
    klee_make_symbolic(&X63, sizeof(char), "X63");
    klee_make_symbolic(&X64, sizeof(char), "X64");
    klee_make_symbolic(&X65, sizeof(char), "X65");
    klee_make_symbolic(&X66, sizeof(char), "X66");
    klee_make_symbolic(&X67, sizeof(char), "X67");
    klee_make_symbolic(&X68, sizeof(char), "X68");
    klee_make_symbolic(&X69, sizeof(char), "X69");
    klee_make_symbolic(&X70, sizeof(char), "X60");
    klee_make_symbolic(&X71, sizeof(char), "X71");
    klee_make_symbolic(&X72, sizeof(char), "X72");
    klee_make_symbolic(&X73, sizeof(char), "X73");
    klee_make_symbolic(&X74, sizeof(char), "X74");
    klee_make_symbolic(&X75, sizeof(char), "X75");
    klee_make_symbolic(&X76, sizeof(char), "X76");
    klee_make_symbolic(&X77, sizeof(char), "X77");
    klee_make_symbolic(&X78, sizeof(char), "X78");
    klee_make_symbolic(&X79, sizeof(char), "X79");
    klee_make_symbolic(&X80, sizeof(char), "X80");
    klee_make_symbolic(&X81, sizeof(char), "X81");
    klee_make_symbolic(&X82, sizeof(char), "X82");
    klee_make_symbolic(&X83, sizeof(char), "X83");
    klee_make_symbolic(&X84, sizeof(char), "X84");
    klee_make_symbolic(&X85, sizeof(char), "X85");
    klee_make_symbolic(&X86, sizeof(char), "X86");
    t = 0;
    X1 = 0L;
    X2 = 0L;
    X3 = 0L;
    X87 = (char)0;
    X88 = (char)0;
    X89 = (char)0;
    X90 = (char)0;
    X91 = (char)0;
    X92 = (char)0;
    X93 = (char)0;
    X94 = (char)0;
    X95 = (char)0;
    X96 = (char)0;
    X97 = (char)0;
    X98 = (char)0;
    X99 = (char)0;
    X100 = (char)0;
    X101 = (char)0;
    X102 = (char)0;
    t = t + 1;
    if (B4) {
      X3 = time;
      t = t + 1;
    }
    if (B4) {
      X2 = time;
      t = t + 1;
    } else {
      if (B6) {
        X2 = time;
        t = t + 1;
      }
    }
    if (X4 != 0L) {
      if ((double)(time - X4) >= 0.5) {
        X53 = (char)0;
        X4 = 0L;
        t = t + 1;
      }
    }
    if (X5 != 0L) {
      if ((double)(time - X5) >= 0.5) {
        X50 = (char)0;
        X5 = 0L;
        t = t + 1;
      }
    }
    if (X6 != 0L) {
      if ((double)(time - X6) >= 0.5) {
        X50 = (char)0;
        X6 = 0L;
        t = t + 1;
      }
    }
    if (X10 != 0L) {
      if ((double)(time - X10) >= 0.5) {
        X10 = 0L;
        t = t + 1;
      }
    }
    if (X11 != 0L) {
      if ((double)(time - X11) >= 0.5) {
        X11 = 0L;
        t = t + 1;
      }
    }
    if (B0) {
      X1 = time;
      t = t + 1;
    } else {
      if (X22 != X24) {
        X1 = time;
        t = t + 1;
      }
    }
    time = 1L;
    stable = (char)0;
    step = (char)0;
    t = t + 1;
    stable = (char)1;
    step = (char)((int)step + 1);
    t = t + 1;
    if ((int)X99 == 1) {
      goto switch_0_1;
    } else {
      if ((int)X99 == 2) {
        goto switch_0_2;
      } else {
        if ((int)X99 == 3) {
          goto switch_0_3;
        } else {
          goto switch_0_default;
          if (0) {
          switch_0_1:
            if (!X81) {
              if (X83) {
                stable = (char)0;
                X15 = 0;
                X99 = (char)2;
                t = t + 1;
                goto switch_0_break;
              }
            }
            goto switch_0_break;
          switch_0_2:
            if (X81) {
              if (!X83) {
                stable = (char)0;
                X15 = -100;
                X99 = (char)1;
                t = t + 1;
                goto switch_0_break;
              }
            }
            if (X84) {
              if (!X86) {
                stable = (char)0;
                X15 = 100;
                X99 = (char)3;
                t = t + 1;
                goto switch_0_break;
              }
            }
            goto switch_0_break;
          switch_0_3:
            if (!X84) {
              if (X86) {
                stable = (char)0;
                X15 = 0;
                X99 = (char)2;
                t = t + 1;
                goto switch_0_break;
              }
            }
            goto switch_0_break;
          switch_0_default:
            stable = (char)0;
            X15 = 0;
            X99 = (char)2;
            t = t + 1;
            goto switch_0_break;
          } else {
          switch_0_break:;
          }
        }
      }
    }
    if (!B10) {
      X90 = (char)3;
      t = t + 1;
    }
    B11 = (char)0;
    t = t + 1;
    if (!B16) {
      X100 = (char)1;
      t = t + 1;
    }
    B17 = (char)0;
    t = t + 1;
    if (!B19) {
      B0 = (char)0;
      X102 = (char)1;
      t = t + 1;
    }
    B20 = (char)0;
    t = t + 1;
    if (!B13) {
      B4 = (char)0;
      B6 = (char)0;
      X91 = (char)2;
      X7 = 0;
      X92 = (char)1;
      B5 = (char)1;
      X93 = (char)1;
      t = t + 1;
    }
    B14 = (char)0;
    B11 = (char)1;
    B17 = (char)1;
    B20 = (char)1;
    B14 = (char)1;
    t = t + 1;
    if ((int)X68 != (int)X70) {
      if (!X77) {
        X60 = X68;
        t = t + 1;
      }
    }
    if ((int)X71 != (int)X72) {
      if (X77) {
        X68 = X71;
        t = t + 1;
      }
    }
    if ((int)X65 != (int)X67) {
      if (!X77) {
        X61 = X65;
        t = t + 1;
      }
    }
    if ((int)X73 != (int)X74) {
      if (X77) {
        X65 = X73;
        t = t + 1;
      }
    }
    B10 = B12;
    B13 = B15;
    B16 = B18;
    B19 = B21;
    X36 = X76;
    X34 = X61;
    X32 = X75;
    X30 = X60;
    t = t + 1;
    X84 = X52;
    X81 = X49;
    X18 = X13;
    X63 = X55;
    X17 = X12;
    X62 = X42;
    X76 = X36;
    X61 = X34;
    X75 = X32;
    X60 = X30;
    X59 = X38;
    X78 = X39;
    X36 = X76;
    X34 = X61;
    X32 = X75;
    X30 = X60;
    t = t + 1;
    if (!B13) {
      if (B15) {
        if (!B14) {
          B4 = (char)0;
          B6 = (char)0;
          t = t + 1;
        }
      }
    }
    if (B13) {
      if (!B10) {
        X90 = (char)3;
        t = t + 1;
      }
      B11 = (char)0;
      t = t + 1;
      if (!B19) {
        B0 = (char)0;
        X102 = (char)1;
        t = t + 1;
      }
      B20 = (char)0;
      B11 = (char)1;
      B20 = (char)1;
      t = t + 1;
      if ((int)X91 == 1) {
        goto switch_1_1;
      } else {
        if ((int)X91 == 2) {
          goto switch_1_2;
        } else {
          if ((int)X91 == 3) {
            goto switch_1_3;
          } else {
            goto switch_1_default;
            if (0) {
            switch_1_1:
              if (X7 == 59) {
                if (!(X9 == 59)) {
                  stable = (char)0;
                  X91 = (char)3;
                  X94 = (char)3;
                  t = t + 1;
                  goto switch_1_break;
                }
              }
              goto switch_1_break;
            switch_1_2:
              if (X39) {
                if (!X41) {
                  if (X49) {
                    stable = (char)0;
                    X50 = (char)0;
                    X6 = time;
                    X91 = (char)3;
                    X94 = (char)3;
                    t = t + 1;
                    goto switch_1_break;
                  }
                }
              }
              if ((int)X87 == 1) {
                goto switch_2_1;
              } else {
                if ((int)X87 == 2) {
                  goto switch_2_2;
                } else {
                  if ((int)X87 == 3) {
                    goto switch_2_3;
                  } else {
                    goto switch_2_default;
                    if (0) {
                    switch_2_1:
                      if (!X43) {
                        stable = (char)0;
                        X50 = (char)0;
                        X87 = (char)3;
                        t = t + 1;
                        goto switch_2_break;
                      }
                      goto switch_2_break;
                    switch_2_2:
                      if (!X46) {
                        stable = (char)0;
                        X53 = (char)0;
                        X87 = (char)3;
                        t = t + 1;
                        goto switch_2_break;
                      }
                      goto switch_2_break;
                    switch_2_3:
                      if (X46) {
                        stable = (char)0;
                        X53 = (char)1;
                        X87 = (char)2;
                        t = t + 1;
                        goto switch_2_break;
                      }
                      if (X43) {
                        stable = (char)0;
                        X50 = (char)1;
                        X87 = (char)1;
                        t = t + 1;
                        goto switch_2_break;
                      }
                      goto switch_2_break;
                    switch_2_default:
                      stable = (char)0;
                      X87 = (char)3;
                      t = t + 1;
                      goto switch_2_break;
                    } else {
                    switch_2_break:;
                    }
                  }
                }
              }
              goto switch_1_break;
            switch_1_3:
              if (X7 > 60) {
                if (!(X9 > 60)) {
                  if (!X26) {
                    if (!X25) {
                      stable = (char)0;
                      X50 = (char)0;
                      X53 = (char)0;
                      X91 = (char)1;
                      t = t + 1;
                      goto switch_1_break;
                    }
                  }
                }
              }
              if (X39) {
                if (!X41) {
                  if (X52) {
                    stable = (char)0;
                    X53 = (char)0;
                    X4 = time;
                    X91 = (char)2;
                    X87 = (char)3;
                    t = t + 1;
                    goto switch_1_break;
                  }
                }
              }
              if (X39) {
                if (!X41) {
                  if (X49) {
                    stable = (char)0;
                    X50 = (char)0;
                    X5 = time;
                    X91 = (char)2;
                    X87 = (char)3;
                    t = t + 1;
                    goto switch_1_break;
                  }
                }
              }
              if ((int)X94 == 1) {
                goto switch_3_1;
              } else {
                if ((int)X94 == 2) {
                  goto switch_3_2;
                } else {
                  if ((int)X94 == 3) {
                    goto switch_3_3;
                  } else {
                    goto switch_3_default;
                    if (0) {
                    switch_3_1:
                      if (X12 >= 405) {
                        stable = (char)0;
                        X53 = (char)0;
                        X94 = (char)3;
                        t = t + 1;
                        goto switch_3_break;
                      }
                      if ((int)X97 == 1) {
                        goto switch_4_1;
                      } else {
                        if ((int)X97 == 2) {
                          goto switch_4_2;
                        } else {
                          goto switch_4_default;
                          if (0) {
                          switch_4_1:
                            if (X43) {
                              if (!X45) {
                                goto _L;
                              } else {
                                goto _L___0;
                              }
                            } else {
                            _L___0:
                              if (X46) {
                                if (!X48) {
                                _L:
                                  stable = (char)0;
                                  X53 = (char)0;
                                  X94 = (char)3;
                                  X97 = (char)0;
                                  t = t + 1;
                                  goto switch_4_break;
                                }
                              }
                            }
                            goto switch_4_break;
                          switch_4_2:
                            if (X43) {
                              if (!X45) {
                                stable = (char)0;
                                X97 = (char)1;
                                t = t + 1;
                                goto switch_4_break;
                              }
                            }
                            if (!X46) {
                              if (X48) {
                                stable = (char)0;
                                X53 = (char)0;
                                X94 = (char)3;
                                X97 = (char)0;
                                t = t + 1;
                                goto switch_4_break;
                              }
                            }
                            goto switch_4_break;
                          switch_4_default:
                            stable = (char)0;
                            X97 = (char)2;
                            t = t + 1;
                            goto switch_4_break;
                          } else {
                          switch_4_break:;
                          }
                        }
                      }
                      goto switch_3_break;
                    switch_3_2:
                      if (X12 <= 0) {
                        stable = (char)0;
                        X50 = (char)0;
                        X94 = (char)3;
                        t = t + 1;
                        goto switch_3_break;
                      }
                      if ((int)X98 == 1) {
                        goto switch_5_1;
                      } else {
                        if ((int)X98 == 2) {
                          goto switch_5_2;
                        } else {
                          goto switch_5_default;
                          if (0) {
                          switch_5_1:
                            if (X46) {
                              if (!X48) {
                                stable = (char)0;
                                X50 = (char)0;
                                X94 = (char)3;
                                t = t + 1;
                                goto switch_5_break;
                              } else {
                                goto _L___1;
                              }
                            } else {
                            _L___1:
                              if (X43) {
                                if (!X45) {
                                  stable = (char)0;
                                  X50 = (char)0;
                                  X94 = (char)3;
                                  t = t + 1;
                                  goto switch_5_break;
                                }
                              }
                            }
                            if ((int)X95 == 1) {
                              goto switch_6_1;
                            } else {
                              if ((int)X95 == 2) {
                                goto switch_6_2;
                              } else {
                                goto switch_6_default;
                                if (0) {
                                switch_6_1:
                                  B23 = (char)0;
                                  t = t + 1;
                                  if (B22) {
                                    stable = (char)0;
                                    X50 = (char)1;
                                    X27 = (char)0;
                                    X95 = (char)2;
                                    X53 = (char)0;
                                    B17 = (char)1;
                                    t = t + 1;
                                    goto switch_6_break;
                                  }
                                  goto switch_6_break;
                                switch_6_2:
                                  if (B24) {
                                    stable = (char)0;
                                    X27 = (char)1;
                                    B23 = (char)1;
                                    X95 = (char)1;
                                    B17 = (char)0;
                                    X50 = (char)0;
                                    X10 = time;
                                    X53 = (char)1;
                                    t = t + 1;
                                    goto switch_6_break;
                                  }
                                  goto switch_6_break;
                                switch_6_default:
                                  stable = (char)0;
                                  X95 = (char)2;
                                  B17 = (char)1;
                                  t = t + 1;
                                  goto switch_6_break;
                                } else {
                                switch_6_break:;
                                }
                              }
                            }
                            goto switch_5_break;
                          switch_5_2:
                            if (!X43) {
                              if (X45) {
                                stable = (char)0;
                                X50 = (char)0;
                                X94 = (char)3;
                                t = t + 1;
                                goto switch_5_break;
                              }
                            }
                            if ((int)X96 == 1) {
                              goto switch_7_1;
                            } else {
                              if ((int)X96 == 2) {
                                goto switch_7_2;
                              } else {
                                goto switch_7_default;
                                if (0) {
                                switch_7_1:
                                  B23 = (char)0;
                                  t = t + 1;
                                  if (B22) {
                                    stable = (char)0;
                                    X28 = (char)0;
                                    X96 = (char)2;
                                    X53 = (char)0;
                                    B17 = (char)1;
                                    X50 = (char)1;
                                    t = t + 1;
                                    goto switch_7_break;
                                  }
                                  goto switch_7_break;
                                switch_7_2:
                                  if (B24) {
                                    stable = (char)0;
                                    X50 = (char)0;
                                    X28 = (char)1;
                                    B23 = (char)1;
                                    X96 = (char)1;
                                    B17 = (char)0;
                                    X11 = time;
                                    X53 = (char)1;
                                    t = t + 1;
                                    goto switch_7_break;
                                  }
                                  if (X46) {
                                    if (!X48) {
                                      stable = (char)0;
                                      X98 = (char)1;
                                      X96 = (char)0;
                                      t = t + 1;
                                      goto switch_7_break;
                                    }
                                  }
                                  goto switch_7_break;
                                switch_7_default:
                                  stable = (char)0;
                                  X96 = (char)2;
                                  B17 = (char)1;
                                  X50 = (char)1;
                                  t = t + 1;
                                  goto switch_7_break;
                                } else {
                                switch_7_break:;
                                }
                              }
                            }
                            goto switch_5_break;
                          switch_5_default:
                            stable = (char)0;
                            X98 = (char)2;
                            X96 = (char)2;
                            B17 = (char)1;
                            X50 = (char)1;
                            t = t + 1;
                            goto switch_5_break;
                          } else {
                          switch_5_break:;
                          }
                        }
                      }
                      goto switch_3_break;
                    switch_3_3:
                      if (X43) {
                        if (!X45) {
                          if (X12 > 0) {
                            stable = (char)0;
                            X94 = (char)2;
                            X98 = (char)2;
                            X96 = (char)2;
                            B17 = (char)1;
                            X50 = (char)1;
                            t = t + 1;
                            goto switch_3_break;
                          }
                        }
                      }
                      if (X46) {
                        if (!X48) {
                          if (X12 < 405) {
                            stable = (char)0;
                            X53 = (char)1;
                            X94 = (char)1;
                            X97 = (char)2;
                            t = t + 1;
                            goto switch_3_break;
                          }
                        }
                      }
                      goto switch_3_break;
                    switch_3_default:
                      stable = (char)0;
                      X94 = (char)3;
                      t = t + 1;
                      goto switch_3_break;
                    } else {
                    switch_3_break:;
                    }
                  }
                }
              }
              goto switch_1_break;
            switch_1_default:
              stable = (char)0;
              X91 = (char)2;
              t = t + 1;
              goto switch_1_break;
            } else {
            switch_1_break:;
            }
          }
        }
      }
      if ((int)X92 == 1) {
        goto switch_8_1;
      } else {
        goto switch_8_default;
        if (0) {
        switch_8_1:
          B5 = (char)0;
          t = t + 1;
          if ((int)step == 1) {
            if (X2 != 0L) {
              if (time - X2 == 1L) {
                if (X49) {
                  goto _L___2;
                } else {
                  if (X52) {
                  _L___2:
                    stable = (char)0;
                    X7 = X7 + 1;
                    X92 = (char)1;
                    B5 = (char)1;
                    X93 = (char)1;
                    t = t + 1;
                    goto switch_8_break;
                  }
                }
              }
            }
          }
          if ((int)X93 == 1) {
            goto switch_9_1;
          } else {
            goto switch_9_default;
            if (0) {
            switch_9_1:
              if ((int)step == 1) {
                if (X3 != 0L) {
                  if (time - X3 == 3L) {
                    if (!X49) {
                      if (!X52) {
                        if (X7 > 0) {
                          stable = (char)0;
                          X7 = X7 - 1;
                          X93 = (char)1;
                          t = t + 1;
                          goto switch_9_break;
                        }
                      }
                    }
                  }
                }
              }
              goto switch_9_break;
            switch_9_default:
              stable = (char)0;
              B5 = (char)1;
              X93 = (char)1;
              t = t + 1;
              goto switch_9_break;
            } else {
            switch_9_break:;
            }
          }
          goto switch_8_break;
        switch_8_default:
          stable = (char)0;
          X7 = 0;
          X92 = (char)1;
          B5 = (char)1;
          X93 = (char)1;
          t = t + 1;
          goto switch_8_break;
        } else {
        switch_8_break:;
        }
      }
      B5 = B4;
      B7 = B6;
      t = t + 1;
    }
    X84 = X52;
    X81 = X49;
    X18 = X13;
    X63 = X55;
    X17 = X12;
    X62 = X42;
    X76 = X36;
    X61 = X34;
    X75 = X32;
    X60 = X30;
    X59 = X38;
    X78 = X39;
    X36 = X76;
    X34 = X61;
    X32 = X75;
    X30 = X60;
    t = t + 1;
    X84 = X52;
    X81 = X49;
    X18 = X13;
    X63 = X55;
    X17 = X12;
    X62 = X42;
    X76 = X36;
    X61 = X34;
    X75 = X32;
    X60 = X30;
    X59 = X38;
    X78 = X39;
    X36 = X76;
    X34 = X61;
    X32 = X75;
    X30 = X60;
    t = t + 1;
    X84 = X52;
    X81 = X49;
    X18 = X13;
    X63 = X55;
    X17 = X12;
    X62 = X42;
    X76 = X36;
    X61 = X34;
    X75 = X32;
    X60 = X30;
    X59 = X38;
    X78 = X39;
    B11 = B10;
    B14 = B13;
    B17 = B16;
    B20 = B19;
    X9 = X7;
    X14 = X13;
    X15 = X16;
    X19 = X18;
    X24 = X22;
    X31 = X30;
    X33 = X32;
    X35 = X34;
    X37 = X36;
    X39 = X40;
    X41 = X39;
    X43 = X44;
    X45 = X43;
    X46 = X47;
    X48 = X46;
    X49 = X50;
    X51 = X49;
    X52 = X53;
    X54 = X52;
    X56 = X55;
    X64 = X63;
    X67 = X65;
    X70 = X68;
    X72 = X71;
    X74 = X73;
    X78 = X79;
    X80 = X78;
    X81 = X82;
    X83 = X81;
    X84 = X85;
    X86 = X84;
    t = t + 1;
    /*  _SLICE(kappa);*/
    return (0);
  }
}
