/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */
#include <stdio.h>
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
int kappa = 0;

int main(void) {
  int date;
  int ch;

  {
    printf("ENTER DATE OF BIRTH AND THEN MONTH NO. codewithc");
    klee_make_symbolic(&date, sizeof(int), "date");
    klee_make_symbolic(&ch, sizeof(int), "ch");
    if (date >= 21) {
      if (ch == 3) {
        printf("YOU ARE A ARIES AND YOUR BIRTHSTONE IS BLOODSTONE");
      } else {
        goto _L;
      }
    } else {
    _L: /* CIL Label */
      if (date <= 20) {
        if (ch == 4) {
          printf("YOU ARE A ARIES AND YOUR BIRTHSTONE IS BLOODSTONE");
        }
      }
    }
    if (date >= 21) {
      if (ch == 4) {
        printf("YOU ARE A TAURUS AND YOUR BIRTHSTONE IS SAPPHIRE");
      } else {
        goto _L___0;
      }
    } else {
    _L___0: /* CIL Label */
      if (date <= 21) {
        if (ch == 5) {
          printf("YOU ARE A TAURUS AND YOUR BIRTHSTONE IS SAPPHIRE");
        }
      }
    }
    if (date >= 22) {
      if (ch == 5) {
        printf("YOU ARE A GEMINI AND YOUR BIRTHSTONE IS AGATE");
      } else {
        goto _L___1;
      }
    } else {
    _L___1: /* CIL Label */
      if (date <= 21) {
        if (ch == 6) {
          printf("YOU ARE A GEMINI AND YOUR BIRTHSTONE IS AGATE");
        }
      }
    }
    if (date >= 22) {
      if (ch == 6) {
        printf("YOU ARE A CANCER AND YOUR BIRTHSTONE IS EMERALD");
      } else {
        goto _L___2;
      }
    } else {
    _L___2: /* CIL Label */
      if (date <= 22) {
        if (ch == 7) {
          printf("YOU ARE A CANCER AND YOUR BIRTHSTONE IS EMERALD");
        }
      }
    }
    if (date >= 23) {
      if (ch == 7) {
        printf("YOU ARE A LEO AND YOUR BIRTHSTONE IS ONYX");
      } else {
        goto _L___3;
      }
    } else {
    _L___3: /* CIL Label */
      if (date <= 22) {
        if (ch == 8) {
          printf("YOU ARE A LEO AND YOUR BIRTHSTONE IS ONYX");
        }
      }
    }
    if (date >= 23) {
      if (ch == 8) {
        printf("YOU ARE A VIRGO AND YOUR BIRTHSTONE IS CARNELIAN");
      } else {
        goto _L___4;
      }
    } else {
    _L___4: /* CIL Label */
      if (date <= 22) {
        if (ch == 9) {
          printf("YOU ARE A VIRGO AND YOUR BIRTHSTONE IS CARNELIAN");
        }
      }
    }
    if (date >= 23) {
      if (ch == 9) {
        printf("YOU ARE A LIBRA AND YOUR BIRTHSTONE IS CHRYSOLITE");
      } else {
        goto _L___5;
      }
    } else {
    _L___5: /* CIL Label */
      if (date <= 23) {
        if (ch == 10) {
          printf("YOU ARE A LIBRA AND YOUR BIRTHSTONE IS CHRYSOLITE");
        }
      }
    }
    if (date >= 24) {
      if (ch == 10) {
        printf("YOU ARE A SCORPIO AND YOUR BIRTHSTONE IS BERYL");
      } else {
        goto _L___6;
      }
    } else {
    _L___6: /* CIL Label */
      if (date <= 21) {
        if (ch == 11) {
          printf("YOU ARE A SCORPIO AND YOUR BIRTHSTONE IS BERYL");
        }
      }
    }
    if (date >= 22) {
      if (ch == 11) {
        printf("YOU ARE A SAGITTARIUS AND YOUR BIRTHSTONE IS TOPAZ");
      } else {
        goto _L___7;
      }
    } else {
    _L___7: /* CIL Label */
      if (date <= 21) {
        if (ch == 12) {
          printf("YOU ARE A SAGITTARIUS AND YOUR BIRTHSTONE IS TOPAZ");
        }
      }
    }
    if (date >= 22) {
      if (ch == 12) {
        printf("YOU ARE A CAPRICORN AND YOUR BIRTHSTONE IS RUBY");
      } else {
        goto _L___8;
      }
    } else {
    _L___8: /* CIL Label */
      if (date <= 21) {
        if (ch == 1) {
          printf("YOU ARE A CAPRICORN AND YOUR BIRTHSTONE IS RUBY");
        }
      }
    }
    if (date >= 22) {
      if (ch == 1) {
        printf("YOU ARE A AQUARIUS AND YOUR BIRTHSTONE IS GARNET");
      } else {
        goto _L___9;
      }
    } else {
    _L___9: /* CIL Label */
      if (date <= 18) {
        if (ch == 2) {
          printf("YOU ARE A AQUARIUS AND YOUR BIRTHSTONE IS GARNET");
        }
      }
    }
    if (date >= 19) {
      if (ch == 2) {
        printf("YOU ARE A PISCES AND YOUR BIRTHSTONE IS AMETHYST");
      } else {
        goto _L___10;
      }
    } else {
    _L___10: /* CIL Label */
      if (date <= 20) {
        if (ch == 3) {
          printf("YOU ARE A PISCES AND YOUR BIRTHSTONE IS AMETHYST");
        }
      }
    }
    /*  _SLICE(kappa);*/
    return (0);
  }
}
