/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */
#include <stdio.h>
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
/* compiler builtin:
   void *__builtin_alloca(unsigned int  ) ;  */
int BOUND = 7;
int kappa = 0;
int input;
int output;
int inputs[5] = {4, 5, 3, 1, 2};
int calculate_output(int input___0);
int calculate_outputm1(int input___0);
int calculate_outputm2(int input___0);
int calculate_outputm3(int input___0);
int calculate_outputm4(int input___0);
int calculate_outputm5(int input___0);
int calculate_outputm6(int input___0);
int calculate_outputm7(int input___0);
int calculate_outputm8(int input___0);
int calculate_outputm9(int input___0);
int calculate_outputm10(int input___0);
int calculate_outputm11(int input___0);
int calculate_outputm12(int input___0);
int calculate_outputm13(int input___0);
int calculate_outputm14(int input___0);
int calculate_outputm15(int input___0);
int calculate_outputm16(int input___0);
int calculate_outputm17(int input___0);
int calculate_outputm18(int input___0);
int calculate_outputm19(int input___0);
int calculate_outputm20(int input___0);
int calculate_outputm21(int input___0);
int calculate_outputm22(int input___0);
int calculate_outputm23(int input___0);
int calculate_outputm24(int input___0);
int calculate_outputm25(int input___0);
int calculate_outputm26(int input___0);
int calculate_outputm27(int input___0);
int a2135605241 = 32;
int a1917497990 = 32;
int a33642816 = 34;
int cf = 1;
int a1033413197 = 7;
int a1354855424 = 35;
int a1268307040 = 4;
int calculate_outputm1(int input___0) {

  {
    if (a33642816 == 33) {
      if (a1917497990 == 33) {
        if (cf == 1) {
          if (input___0 == 3) {
            cf = 0;
            a33642816 = 35;
            a1268307040 = 4;
          }
        }
      }
    }
    if (a1917497990 == 33) {
      if (input___0 == 1) {
        if (cf == 1) {
          if (a33642816 == 33) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 34;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm2(int input___0) {

  {
    if (a33642816 == 33) {
      if (cf == 1) {
        if (a1917497990 == 32) {
          if (input___0 == 4) {
            cf = 0;
            a33642816 = 32;
            a1033413197 = 4;
          }
        }
      }
    }
    if (input___0 == 3) {
      if (cf == 1) {
        if (a33642816 == 33) {
          if (a1917497990 == 32) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 36;
          }
        }
      }
    }
    if (cf == 1) {
      if (a33642816 == 33) {
        if (a1917497990 == 32) {
          if (input___0 == 5) {
            cf = 0;
            a33642816 = 32;
            a1033413197 = 4;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm3(int input___0) {

  {
    if (input___0 == 3) {
      if (a33642816 == 33) {
        if (cf == 1) {
          if (a1917497990 == 34) {
            cf = 0;
            a33642816 = 32;
            a1033413197 = 6;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm4(int input___0) {

  {
    if (input___0 == 2) {
      if (cf == 1) {
        if (a33642816 == 33) {
          if (a1917497990 == 35) {
            cf = 0;
          }
        }
      }
    }
    if (a33642816 == 33) {
      if (a1917497990 == 35) {
        if (input___0 == 5) {
          if (cf == 1) {
            cf = 0;
            a33642816 = 35;
            a1268307040 = 11;
          }
        }
      }
    }
    if (cf == 1) {
      if (input___0 == 1) {
        if (a1917497990 == 35) {
          if (a33642816 == 33) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 33;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm5(int input___0) {

  {
    if (cf == 1) {
      if (a33642816 == 33) {
        if (input___0 == 5) {
          if (a1917497990 == 36) {
            cf = 0;
            a1917497990 = 33;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm6(int input___0) {

  {
    if (a1033413197 == 1) {
      if (input___0 == 1) {
        if (cf == 1) {
          if (a33642816 == 32) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 36;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm7(int input___0) {

  {
    if (input___0 == 5) {
      if (a1033413197 == 2) {
        if (a33642816 == 32) {
          if (cf == 1) {
            cf = 0;
            a33642816 = 33;
            a1917497990 = 32;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm8(int input___0) {

  {
    if (input___0 == 1) {
      if (a1033413197 == 4) {
        if (a33642816 == 32) {
          if (cf == 1) {
            cf = 0;
            a1033413197 = 1;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm9(int input___0) {

  {
    if (a33642816 == 32) {
      if (input___0 == 2) {
        if (cf == 1) {
          if (a1033413197 == 5) {
            cf = 0;
            a33642816 = 35;
            a1268307040 = 11;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm10(int input___0) {

  {
    if (a1033413197 == 6) {
      if (input___0 == 2) {
        if (cf == 1) {
          if (a33642816 == 32) {
            cf = 0;
            a1033413197 = 5;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm11(int input___0) {

  {
    if (input___0 == 1) {
      if (cf == 1) {
        if (a1033413197 == 7) {
          if (a33642816 == 32) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 36;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm12(int input___0) {

  {
    if (cf == 1) {
      if (a2135605241 == 33) {
        if (a33642816 == 34) {
          if (input___0 == 2) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 33;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm13(int input___0) {

  {
    if (a33642816 == 34) {
      if (input___0 == 4) {
        if (cf == 1) {
          if (a2135605241 == 32) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 35;
          }
        }
      }
    }
    if (cf == 1) {
      if (a33642816 == 34) {
        if (input___0 == 2) {
          if (a2135605241 == 32) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 33;
          }
        }
      }
    }
    if (a2135605241 == 32) {
      if (cf == 1) {
        if (input___0 == 3) {
          if (a33642816 == 34) {
            cf = 0;
            a33642816 = 35;
            a1268307040 = 8;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm14(int input___0) {

  {
    if (cf == 1) {
      if (a33642816 == 34) {
        if (input___0 == 3) {
          if (a2135605241 == 34) {
            cf = 0;
            a33642816 = 35;
            a1268307040 = 10;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm15(int input___0) {

  {
    if (a2135605241 == 35) {
      if (input___0 == 4) {
        if (cf == 1) {
          if (a33642816 == 34) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 35;
          }
        }
      }
    }
    if (a33642816 == 34) {
      if (a2135605241 == 35) {
        if (cf == 1) {
          if (input___0 == 1) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 35;
          }
        }
      }
    }
    if (a2135605241 == 35) {
      if (cf == 1) {
        if (input___0 == 3) {
          if (a33642816 == 34) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 32;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm16(int input___0) {

  {
    if (input___0 == 3) {
      if (a2135605241 == 36) {
        if (cf == 1) {
          if (a33642816 == 34) {
            cf = 0;
            a33642816 = 35;
            a1268307040 = 6;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm17(int input___0) {

  {
    if (a1268307040 == 4) {
      if (input___0 == 3) {
        if (cf == 1) {
          if (a33642816 == 35) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 36;
          }
        }
      }
    }
    if (input___0 == 5) {
      if (a1268307040 == 4) {
        if (a33642816 == 35) {
          if (cf == 1) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 36;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm18(int input___0) {

  {
    if (a33642816 == 35) {
      if (input___0 == 3) {
        if (cf == 1) {
          if (a1268307040 == 5) {
            cf = 0;
          }
        }
      }
    }
    if (input___0 == 5) {
      if (cf == 1) {
        if (a33642816 == 35) {
          if (a1268307040 == 5) {
            cf = 0;
            a1268307040 = 6;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm19(int input___0) {

  {
    if (input___0 == 3) {
      if (a1268307040 == 6) {
        if (cf == 1) {
          if (a33642816 == 35) {
            cf = 0;
            a33642816 = 32;
            a1033413197 = 7;
          }
        }
      }
    }
    if (input___0 == 1) {
      if (a33642816 == 35) {
        if (cf == 1) {
          if (a1268307040 == 6) {
            cf = 0;
            a33642816 = 33;
            a1917497990 = 36;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm20(int input___0) {

  {
    if (input___0 == 4) {
      if (cf == 1) {
        if (a33642816 == 35) {
          if (a1268307040 == 7) {
            cf = 0;
            a33642816 = 36;
            a1354855424 = 35;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm21(int input___0) {

  {
    if (cf == 1) {
      if (input___0 == 3) {
        if (a33642816 == 35) {
          if (a1268307040 == 8) {
            cf = 0;
            a1268307040 = 5;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm22(int input___0) {

  {
    if (a1268307040 == 10) {
      if (input___0 == 5) {
        if (a33642816 == 35) {
          if (cf == 1) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 36;
          }
        }
      }
    }
    if (input___0 == 3) {
      if (cf == 1) {
        if (a33642816 == 35) {
          if (a1268307040 == 10) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 36;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm23(int input___0) {

  {
    if (a1268307040 == 11) {
      if (a33642816 == 35) {
        if (input___0 == 2) {
          if (cf == 1) {
            cf = 0;
            a33642816 = 33;
            a1917497990 = 34;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm24(int input___0) {

  {
    if (input___0 == 2) {
      if (a33642816 == 36) {
        if (cf == 1) {
          if (a1354855424 == 33) {
            cf = 0;
            a33642816 = 33;
            a1917497990 = 35;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm25(int input___0) {

  {
    if (input___0 == 1) {
      if (a33642816 == 36) {
        if (cf == 1) {
          if (a1354855424 == 32) {
            cf = 0;
            a33642816 = 34;
            a2135605241 = 35;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm26(int input___0) {

  {
    if (a1354855424 == 35) {
      if (a33642816 == 36) {
        if (input___0 == 3) {
          if (cf == 1) {
            cf = 0;
            a33642816 = 35;
            a1268307040 = 7;
          }
        }
      }
    }
    if (input___0 == 5) {
      if (cf == 1) {
        if (a33642816 == 36) {
          if (a1354855424 == 35) {
            cf = 0;
            a33642816 = 32;
            a1033413197 = 4;
          }
        }
      }
    }
    if (input___0 == 4) {
      if (cf == 1) {
        if (a33642816 == 36) {
          if (a1354855424 == 35) {
            cf = 0;
            a1354855424 = 32;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm27(int input___0) {

  {
    if (a33642816 == 36) {
      if (a1354855424 == 36) {
        if (cf == 1) {
          if (input___0 == 5) {
            cf = 0;
            a33642816 = 32;
            a1033413197 = 1;
          }
        }
      }
    }
    if (a33642816 == 36) {
      if (cf == 1) {
        if (a1354855424 == 36) {
          if (input___0 == 1) {
            cf = 0;
            a33642816 = 32;
            a1033413197 = 2;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_output(int input___0) {

  {
    cf = 1;
    if (a33642816 == 33) {
      if (cf == 1) {
        if (a1917497990 == 33) {
          if (cf == 1) {
            calculate_outputm1(input___0);
          }
        }
        if (a1917497990 == 32) {
          if (cf == 1) {
            calculate_outputm2(input___0);
          }
        }
        if (a1917497990 == 34) {
          if (cf == 1) {
            calculate_outputm3(input___0);
          }
        }
        if (a1917497990 == 35) {
          if (cf == 1) {
            calculate_outputm4(input___0);
          }
        }
        if (a1917497990 == 36) {
          if (cf == 1) {
            calculate_outputm5(input___0);
          }
        }
      }
    }
    if (a33642816 == 32) {
      if (cf == 1) {
        if (cf == 1) {
          if (a1033413197 == 1) {
            calculate_outputm6(input___0);
          }
        }
        if (a1033413197 == 2) {
          if (cf == 1) {
            calculate_outputm7(input___0);
          }
        }
        if (cf == 1) {
          if (a1033413197 == 4) {
            calculate_outputm8(input___0);
          }
        }
        if (cf == 1) {
          if (a1033413197 == 5) {
            calculate_outputm9(input___0);
          }
        }
        if (a1033413197 == 6) {
          if (cf == 1) {
            calculate_outputm10(input___0);
          }
        }
        if (cf == 1) {
          if (a1033413197 == 7) {
            calculate_outputm11(input___0);
          }
        }
      }
    }
    if (cf == 1) {
      if (a33642816 == 34) {
        if (a2135605241 == 33) {
          if (cf == 1) {
            calculate_outputm12(input___0);
          }
        }
        if (cf == 1) {
          if (a2135605241 == 32) {
            calculate_outputm13(input___0);
          }
        }
        if (cf == 1) {
          if (a2135605241 == 34) {
            calculate_outputm14(input___0);
          }
        }
        if (a2135605241 == 35) {
          if (cf == 1) {
            calculate_outputm15(input___0);
          }
        }
        if (a2135605241 == 36) {
          if (cf == 1) {
            calculate_outputm16(input___0);
          }
        }
      }
    }
    if (cf == 1) {
      if (a33642816 == 35) {
        if (a1268307040 == 4) {
          if (cf == 1) {
            calculate_outputm17(input___0);
          }
        }
        if (cf == 1) {
          if (a1268307040 == 5) {
            calculate_outputm18(input___0);
          }
        }
        if (cf == 1) {
          if (a1268307040 == 6) {
            calculate_outputm19(input___0);
          }
        }
        if (a1268307040 == 7) {
          if (cf == 1) {
            calculate_outputm20(input___0);
          }
        }
        if (cf == 1) {
          if (a1268307040 == 8) {
            calculate_outputm21(input___0);
          }
        }
        if (a1268307040 == 10) {
          if (cf == 1) {
            calculate_outputm22(input___0);
          }
        }
        if (a1268307040 == 11) {
          if (cf == 1) {
            calculate_outputm23(input___0);
          }
        }
      }
    }
    if (a33642816 == 36) {
      if (cf == 1) {
        if (a1354855424 == 33) {
          if (cf == 1) {
            calculate_outputm24(input___0);
          }
        }
        if (cf == 1) {
          if (a1354855424 == 32) {
            calculate_outputm25(input___0);
          }
        }
        if (a1354855424 == 35) {
          if (cf == 1) {
            calculate_outputm26(input___0);
          }
        }
        if (a1354855424 == 36) {
          if (cf == 1) {
            calculate_outputm27(input___0);
          }
        }
      }
    }
    if (cf == 1) {
    }
    return (0);
  }
}

int main(void) {
  int *symb;
  unsigned int __lengthofsymb;
  void *tmp;
  int FLAG;

  {
    __lengthofsymb = (unsigned int)BOUND;
    tmp = __builtin_alloca(sizeof(*symb) * __lengthofsymb);
    symb = (int *)tmp;
    klee_make_symbolic(symb, sizeof(int) * (unsigned int)BOUND, "symb");
    FLAG = 0;
    while (FLAG < BOUND) {
      if (*(symb + FLAG) != 4) {
        if (*(symb + FLAG) != 5) {
          if (*(symb + FLAG) != 3) {
            if (*(symb + FLAG) != 1) {
              if (*(symb + FLAG) != 2) {
                return (-2);
              }
            }
          }
        }
      }
      calculate_output(*(symb + FLAG));
      FLAG = FLAG + 1;
    }
    /*  _SLICE(kappa);*/
    return (0);
  }
}
