/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */
#include <stdio.h>
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
/* compiler builtin:
   void *__builtin_alloca(unsigned int  ) ;  */
int BOUND = 7;
int kappa = 0;
int input;
int output;
int inputs[5] = {2, 5, 3, 1, 4};
int calculate_output(int input___0);
int calculate_outputm1(int input___0);
int calculate_outputm2(int input___0);
int calculate_outputm3(int input___0);
int calculate_outputm4(int input___0);
int calculate_outputm5(int input___0);
int calculate_outputm6(int input___0);
int calculate_outputm7(int input___0);
int calculate_outputm8(int input___0);
int calculate_outputm9(int input___0);
int calculate_outputm10(int input___0);
int calculate_outputm11(int input___0);
int calculate_outputm12(int input___0);
int calculate_outputm13(int input___0);
int calculate_outputm14(int input___0);
int calculate_outputm15(int input___0);
int calculate_outputm16(int input___0);
int calculate_outputm17(int input___0);
int calculate_outputm18(int input___0);
int calculate_outputm19(int input___0);
int calculate_outputm20(int input___0);
int a167 = 33;
int a52 = 9;
int a166 = 33;
int a176 = 7;
int a175 = 6;
int cf = 1;
int a62 = 32;
int calculate_outputm1(int input___0) {

  {
    if (cf == 1) {
      if (a166 == 33) {
        if (input___0 == 3) {
          if (a176 == 6) {
            cf = 0;
            a166 = 36;
            a62 = 33;
          }
        }
      }
    }
    if (a166 == 33) {
      if (input___0 == 2) {
        if (cf == 1) {
          if (a176 == 6) {
            cf = 0;
          }
        }
      }
    }
    if (cf == 1) {
      if (a166 == 33) {
        if (input___0 == 4) {
          if (a176 == 6) {
            cf = 0;
            a166 = 32;
            a52 = 9;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm2(int input___0) {

  {
    if (a166 == 33) {
      if (cf == 1) {
        if (input___0 == 4) {
          if (a176 == 7) {
            cf = 0;
            a166 = 36;
            a62 = 33;
          }
        }
      }
    }
    if (a176 == 7) {
      if (input___0 == 3) {
        if (a166 == 33) {
          if (cf == 1) {
            cf = 0;
            a176 = 11;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm3(int input___0) {

  {
    if (input___0 == 5) {
      if (cf == 1) {
        if (a166 == 33) {
          if (a176 == 8) {
            cf = 0;
            a166 = 35;
            a175 = 6;
          }
        }
      }
    }
    if (a166 == 33) {
      if (cf == 1) {
        if (input___0 == 2) {
          if (a176 == 8) {
            cf = 0;
            a166 = 36;
            a62 = 32;
          }
        }
      }
    }
    if (a176 == 8) {
      if (cf == 1) {
        if (input___0 == 4) {
          if (a166 == 33) {
            cf = 0;
            a166 = 36;
            a62 = 33;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm4(int input___0) {

  {
    if (input___0 == 1) {
      if (a166 == 33) {
        if (cf == 1) {
          if (a176 == 10) {
            cf = 0;
            a176 = 12;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm5(int input___0) {

  {
    if (a176 == 11) {
      if (input___0 == 5) {
        if (a166 == 33) {
          if (cf == 1) {
            cf = 0;
            a166 = 34;
            a167 = 32;
          }
        }
      }
    }
    if (input___0 == 2) {
      if (cf == 1) {
        if (a176 == 11) {
          if (a166 == 33) {
            cf = 0;
            a176 = 10;
          }
        }
      }
    }
    if (a166 == 33) {
      if (input___0 == 1) {
        if (cf == 1) {
          if (a176 == 11) {
            cf = 0;
            a166 = 35;
            a175 = 8;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm6(int input___0) {

  {
    if (a176 == 12) {
      if (a166 == 33) {
        if (cf == 1) {
          if (input___0 == 4) {
            cf = 0;
          }
        }
      }
    }
    if (a176 == 12) {
      if (input___0 == 2) {
        if (cf == 1) {
          if (a166 == 33) {
            cf = 0;
            a166 = 36;
            a62 = 32;
          }
        }
      }
    }
    if (a176 == 12) {
      if (a166 == 33) {
        if (input___0 == 3) {
          if (cf == 1) {
            cf = 0;
            a176 = 10;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm7(int input___0) {

  {
    if (a52 == 5) {
      if (input___0 == 3) {
        if (a166 == 32) {
          if (cf == 1) {
            cf = 0;
            a166 = 36;
            a62 = 32;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm8(int input___0) {

  {
    if (input___0 == 4) {
      if (a166 == 32) {
        if (cf == 1) {
          if (a52 == 7) {
            cf = 0;
          }
        }
      }
    }
    if (a52 == 7) {
      if (a166 == 32) {
        if (cf == 1) {
          if (input___0 == 5) {
            cf = 0;
            a166 = 35;
            a175 = 8;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm9(int input___0) {

  {
    if (a166 == 32) {
      if (input___0 == 4) {
        if (cf == 1) {
          if (a52 == 8) {
            cf = 0;
            a52 = 9;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm10(int input___0) {

  {
    if (input___0 == 3) {
      if (a52 == 9) {
        if (cf == 1) {
          if (a166 == 32) {
            cf = 0;
          }
        }
      }
    }
    if (a52 == 9) {
      if (input___0 == 2) {
        if (cf == 1) {
          if (a166 == 32) {
            cf = 0;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm11(int input___0) {

  {
    if (input___0 == 1) {
      if (a167 == 33) {
        if (a166 == 34) {
          if (cf == 1) {
            cf = 0;
            a166 = 36;
            a62 = 33;
          }
        }
      }
    }
    if (cf == 1) {
      if (a167 == 33) {
        if (input___0 == 5) {
          if (a166 == 34) {
            cf = 0;
            a166 = 36;
            a62 = 35;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm12(int input___0) {

  {
    if (cf == 1) {
      if (a167 == 32) {
        if (input___0 == 4) {
          if (a166 == 34) {
            cf = 0;
            a167 = 35;
          }
        }
      }
    }
    if (cf == 1) {
      if (input___0 == 1) {
        if (a167 == 32) {
          if (a166 == 34) {
            cf = 0;
            a166 = 32;
            a52 = 5;
          }
        }
      }
    }
    if (input___0 == 5) {
      if (cf == 1) {
        if (a167 == 32) {
          if (a166 == 34) {
            cf = 0;
            a167 = 34;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm13(int input___0) {

  {
    if (a167 == 34) {
      if (cf == 1) {
        if (input___0 == 1) {
          if (a166 == 34) {
            cf = 0;
            a166 = 32;
            a52 = 9;
          }
        }
      }
    }
    if (a166 == 34) {
      if (input___0 == 4) {
        if (cf == 1) {
          if (a167 == 34) {
            cf = 0;
            a166 = 33;
            a176 = 11;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm14(int input___0) {

  {
    if (a166 == 34) {
      if (input___0 == 5) {
        if (a167 == 35) {
          if (cf == 1) {
            cf = 0;
            a167 = 32;
          }
        }
      }
    }
    if (a167 == 35) {
      if (cf == 1) {
        if (a166 == 34) {
          if (input___0 == 3) {
            cf = 0;
            a166 = 36;
            a62 = 32;
          }
        }
      }
    }
    if (input___0 == 2) {
      if (a166 == 34) {
        if (cf == 1) {
          if (a167 == 35) {
            cf = 0;
            a166 = 36;
            a62 = 32;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm15(int input___0) {

  {
    if (input___0 == 1) {
      if (cf == 1) {
        if (a166 == 35) {
          if (a175 == 4) {
            cf = 0;
            a166 = 33;
            a176 = 11;
          }
        }
      }
    }
    if (a175 == 4) {
      if (a166 == 35) {
        if (cf == 1) {
          if (input___0 == 2) {
            cf = 0;
            a175 = 8;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm16(int input___0) {

  {
    if (cf == 1) {
      if (a175 == 6) {
        if (input___0 == 2) {
          if (a166 == 35) {
            cf = 0;
            a166 = 33;
            a176 = 8;
          }
        }
      }
    }
    if (input___0 == 1) {
      if (a166 == 35) {
        if (cf == 1) {
          if (a175 == 6) {
            cf = 0;
            a166 = 33;
            a176 = 6;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm17(int input___0) {

  {
    if (a166 == 35) {
      if (input___0 == 5) {
        if (cf == 1) {
          if (a175 == 8) {
            cf = 0;
            a166 = 32;
            a52 = 7;
          }
        }
      }
    }
    if (a166 == 35) {
      if (cf == 1) {
        if (input___0 == 3) {
          if (a175 == 8) {
            cf = 0;
            a175 = 4;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm18(int input___0) {

  {
    if (a166 == 36) {
      if (cf == 1) {
        if (input___0 == 1) {
          if (a62 == 33) {
            cf = 0;
            a62 = 35;
          }
        }
      }
    }
    if (a166 == 36) {
      if (cf == 1) {
        if (a62 == 33) {
          if (input___0 == 3) {
            cf = 0;
            a166 = 35;
            a175 = 6;
          }
        }
      }
    }
    if (a62 == 33) {
      if (cf == 1) {
        if (input___0 == 4) {
          if (a166 == 36) {
            cf = 0;
            a166 = 32;
            a52 = 8;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm19(int input___0) {

  {
    if (a166 == 36) {
      if (a62 == 32) {
        if (cf == 1) {
          if (input___0 == 3) {
            cf = 0;
            a62 = 33;
          }
        }
      }
    }
    if (input___0 == 5) {
      if (a62 == 32) {
        if (a166 == 36) {
          if (cf == 1) {
            cf = 0;
          }
        }
      }
    }
    if (a166 == 36) {
      if (cf == 1) {
        if (a62 == 32) {
          if (input___0 == 1) {
            cf = 0;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm20(int input___0) {

  {
    if (input___0 == 3) {
      if (a166 == 36) {
        if (cf == 1) {
          if (a62 == 35) {
            cf = 0;
            a62 = 32;
          }
        }
      }
    }
    if (input___0 == 1) {
      if (cf == 1) {
        if (a166 == 36) {
          if (a62 == 35) {
            cf = 0;
            a166 = 34;
            a167 = 33;
          }
        }
      }
    }
    return (0);
  }
}
int calculate_output(int input___0) {

  {
    cf = 1;
    if (a166 == 33) {
      if (cf == 1) {
        if (a176 == 6) {
          if (cf == 1) {
            calculate_outputm1(input___0);
          }
        }
        if (cf == 1) {
          if (a176 == 7) {
            calculate_outputm2(input___0);
          }
        }
        if (a176 == 8) {
          if (cf == 1) {
            calculate_outputm3(input___0);
          }
        }
        if (cf == 1) {
          if (a176 == 10) {
            calculate_outputm4(input___0);
          }
        }
        if (a176 == 11) {
          if (cf == 1) {
            calculate_outputm5(input___0);
          }
        }
        if (a176 == 12) {
          if (cf == 1) {
            calculate_outputm6(input___0);
          }
        }
      }
    }
    if (a166 == 32) {
      if (cf == 1) {
        if (a52 == 5) {
          if (cf == 1) {
            calculate_outputm7(input___0);
          }
        }
        if (cf == 1) {
          if (a52 == 7) {
            calculate_outputm8(input___0);
          }
        }
        if (cf == 1) {
          if (a52 == 8) {
            calculate_outputm9(input___0);
          }
        }
        if (cf == 1) {
          if (a52 == 9) {
            calculate_outputm10(input___0);
          }
        }
      }
    }
    if (a166 == 34) {
      if (cf == 1) {
        if (cf == 1) {
          if (a167 == 33) {
            calculate_outputm11(input___0);
          }
        }
        if (a167 == 32) {
          if (cf == 1) {
            calculate_outputm12(input___0);
          }
        }
        if (a167 == 34) {
          if (cf == 1) {
            calculate_outputm13(input___0);
          }
        }
        if (cf == 1) {
          if (a167 == 35) {
            calculate_outputm14(input___0);
          }
        }
      }
    }
    if (cf == 1) {
      if (a166 == 35) {
        if (cf == 1) {
          if (a175 == 4) {
            calculate_outputm15(input___0);
          }
        }
        if (cf == 1) {
          if (a175 == 6) {
            calculate_outputm16(input___0);
          }
        }
        if (cf == 1) {
          if (a175 == 8) {
            calculate_outputm17(input___0);
          }
        }
      }
    }
    if (a166 == 36) {
      if (cf == 1) {
        if (cf == 1) {
          if (a62 == 33) {
            calculate_outputm18(input___0);
          }
        }
        if (a62 == 32) {
          if (cf == 1) {
            calculate_outputm19(input___0);
          }
        }
        if (cf == 1) {
          if (a62 == 35) {
            calculate_outputm20(input___0);
          }
        }
      }
    }
    if (cf == 1) {
    }
    return (0);
  }
}

int main(void) {
  int *symb;
  unsigned int __lengthofsymb;
  void *tmp;
  int FLAG;

  {
    __lengthofsymb = (unsigned int)BOUND;
    tmp = __builtin_alloca(sizeof(*symb) * __lengthofsymb);
    symb = (int *)tmp;
    klee_make_symbolic(symb, sizeof(int) * (unsigned int)BOUND, "symb");
    FLAG = 0;
    while (FLAG < BOUND) {
      if (*(symb + FLAG) != 2) {
        if (*(symb + FLAG) != 5) {
          if (*(symb + FLAG) != 3) {
            if (*(symb + FLAG) != 1) {
              if (*(symb + FLAG) != 4) {
                return (-2);
              }
            }
          }
        }
      }
      calculate_output(*(symb + FLAG));
      FLAG = FLAG + 1;
    }
    /*  _SLICE(kappa);*/
    return (0);
  }
}
