/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */
#include <stdio.h>
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
/* compiler builtin:
   void *__builtin_alloca(unsigned int  ) ;  */
int BOUND = 10;
int m_initSign = 1;
int m_initVerify = 2;
int m_Signature = 3;
int m_sign = 4;
int m_verify = 5;
int m_update = 6;
int kappa = 0;

int main() {
  int dummy;
  int q;
  int FLAG;
  int i;
  int method_id;
  int this_state;
  int(*symb)[22];
  unsigned int __lengthofsymb;
  void *tmp;
  int FLAG___0;

  {
    dummy = 1;
    q = 0;
    FLAG = 0;
    i = 0;
    this_state = 0;
    __lengthofsymb = (unsigned int)BOUND;
    tmp = __builtin_alloca(sizeof(*symb) * __lengthofsymb);
    symb = (int(*)[22])tmp;
    klee_make_symbolic(symb, (sizeof(int) * (unsigned int)BOUND) * 22U, "symb");
    FLAG___0 = 0;
    while (FLAG___0 < BOUND) {
      if (q == 0) {
        if ((*(symb + FLAG___0))[1]) {
          if (dummy == 1) {
            method_id = 3;
            if (dummy != 1) {
              goto ERROR;
            }
            q = 2;
            this_state = 0;
          }
          goto __Cont;
        }
        goto __Cont;
      }
      if (q == 1) {
        if ((*(symb + FLAG___0))[2]) {
          if (dummy == 1) {
            method_id = 4;
            if (this_state == 2) {
              goto ERROR;
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[3]) {
          if (dummy == 1) {
            method_id = 5;
            if (this_state == 3) {
              goto ERROR;
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[4]) {
          if (dummy == 1) {
            method_id = 6;
            if (this_state == 2) {
              if (this_state != 3) {
                goto ERROR;
              } else {
                goto _L;
              }
            } else {
            _L: /* CIL Label */
              if (this_state == 3) {
                goto ERROR;
              }
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        goto __Cont;
      }
      if (q == 2) {
        if ((*(symb + FLAG___0))[5]) {
          if (dummy == 1) {
            method_id = 1;
            if (dummy != 1) {
              goto ERROR;
            }
            q = 3;
            this_state = 2;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[6]) {
          if (dummy == 1) {
            method_id = 2;
            if (dummy != 1) {
              goto ERROR;
            }
            q = 4;
            this_state = 3;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[7]) {
          if (dummy == 1) {
            method_id = 4;
            if (this_state == 2) {
              goto ERROR;
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[8]) {
          if (dummy == 1) {
            method_id = 5;
            if (this_state == 3) {
              goto ERROR;
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[9]) {
          if (dummy == 1) {
            method_id = 6;
            if (this_state == 2) {
              if (this_state != 3) {
                goto ERROR;
              } else {
                goto _L___0;
              }
            } else {
            _L___0: /* CIL Label */
              if (this_state == 3) {
                goto ERROR;
              }
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        goto __Cont;
      }
      if (q == 3) {
        if ((*(symb + FLAG___0))[10]) {
          if (dummy == 1) {
            method_id = 1;
            if (dummy != 1) {
              goto ERROR;
            }
            q = 3;
            this_state = 2;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[11]) {
          if (dummy == 1) {
            method_id = 2;
            if (dummy != 1) {
              goto ERROR;
            }
            q = 4;
            this_state = 3;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[12]) {
          if (dummy == 1) {
            method_id = 4;
            if (this_state != 2) {
              goto ERROR;
            }
            q = 3;
            this_state = this_state;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[13]) {
          if (dummy == 1) {
            method_id = 5;
            if (this_state == 3) {
              goto ERROR;
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[14]) {
          if (dummy == 1) {
            if (this_state == 2) {
              if (this_state != 3) {
                goto _L___1;
              } else {
                goto _L___2;
              }
            } else {
            _L___2: /* CIL Label */
              if (this_state != 2) {
                if (this_state != 3) {
                _L___1: /* CIL Label */
                  method_id = 6;
                  if (this_state != 2) {
                    if (this_state != 3) {
                      goto ERROR;
                    }
                  }
                  q = 3;
                  this_state = this_state;
                }
              }
            }
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[15]) {
          if (dummy == 1) {
            if (this_state == 2) {
              if (this_state != 3) {
                goto _L___4;
              } else {
                goto _L___5;
              }
            } else {
            _L___5: /* CIL Label */
              if (this_state != 2) {
                if (this_state != 3) {
                _L___4: /* CIL Label */
                  if (this_state == 3) {
                    goto _L___3;
                  } else {
                    if (this_state != 2) {
                      if (this_state != 3) {
                      _L___3: /* CIL Label */
                        method_id = 6;
                        if (this_state != 2) {
                          if (this_state != 3) {
                            goto ERROR;
                          }
                        }
                        q = 3;
                        this_state = this_state;
                      }
                    }
                  }
                }
              }
            }
          }
          goto __Cont;
        }
        goto __Cont;
      }
      if (q == 4) {
        if ((*(symb + FLAG___0))[16]) {
          if (dummy == 1) {
            method_id = 1;
            if (dummy != 1) {
              goto ERROR;
            }
            q = 3;
            this_state = 2;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[17]) {
          if (dummy == 1) {
            method_id = 2;
            if (dummy != 1) {
              goto ERROR;
            }
            q = 4;
            this_state = 3;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[18]) {
          if (dummy == 1) {
            method_id = 4;
            if (this_state == 2) {
              goto ERROR;
            }
            q = 1;
            break;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[19]) {
          if (dummy == 1) {
            method_id = 5;
            if (this_state != 3) {
              goto ERROR;
            }
            q = 4;
            this_state = this_state;
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[20]) {
          if (dummy == 1) {
            if (this_state == 2) {
              if (this_state != 3) {
                goto _L___6;
              } else {
                goto _L___7;
              }
            } else {
            _L___7: /* CIL Label */
              if (this_state != 2) {
                if (this_state != 3) {
                _L___6: /* CIL Label */
                  method_id = 6;
                  if (this_state != 2) {
                    if (this_state != 3) {
                      goto ERROR;
                    }
                  }
                  q = 4;
                  this_state = this_state;
                }
              }
            }
          }
          goto __Cont;
        }
        if ((*(symb + FLAG___0))[21]) {
          if (dummy == 1) {
            if (this_state == 2) {
              if (this_state != 3) {
                goto _L___9;
              } else {
                goto _L___10;
              }
            } else {
            _L___10: /* CIL Label */
              if (this_state != 2) {
                if (this_state != 3) {
                _L___9: /* CIL Label */
                  if (this_state == 3) {
                    goto _L___8;
                  } else {
                    if (this_state != 2) {
                      if (this_state != 3) {
                      _L___8: /* CIL Label */
                        method_id = 6;
                        if (this_state != 2) {
                          if (this_state != 3) {
                            goto ERROR;
                          }
                        }
                        q = 4;
                        this_state = this_state;
                      }
                    }
                  }
                }
              }
            }
          }
          goto __Cont;
        }
        goto __Cont;
      }
    __Cont: /* CIL Label */
      FLAG___0 = FLAG___0 + 1;
    }
  ERROR:
    /*  _SLICE(kappa);*/
    return (0);
  }
}
