/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */
#include <stdio.h>
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
/* compiler builtin:
   void *__builtin_alloca(unsigned int  ) ;  */
int BOUND = 7;
int kappa = 0;
int input;
int output;
int inputs[10] = {5, 6, 1, 7, 2, 8, 3, 9, 10, 4};
int errorCheck(void);
int calculate_output(int input___0);
int calculate_outputm1(int input___0);
int calculate_outputm2(int input___0);
int calculate_outputm3(int input___0);
int calculate_outputm4(int input___0);
int calculate_outputm5(int input___0);
int calculate_outputm6(int input___0);
int calculate_outputm7(int input___0);
int calculate_outputm8(int input___0);
int calculate_outputm9(int input___0);
int calculate_outputm10(int input___0);
int calculate_outputm11(int input___0);
int calculate_outputm12(int input___0);
int calculate_outputm13(int input___0);
int calculate_outputm14(int input___0);
int calculate_outputm15(int input___0);
int calculate_outputm16(int input___0);
int calculate_outputm17(int input___0);
int calculate_outputm18(int input___0);
int calculate_outputm19(int input___0);
int calculate_outputm20(int input___0);
int calculate_outputm21(int input___0);
int calculate_outputm22(int input___0);
int calculate_outputm23(int input___0);
int calculate_outputm24(int input___0);
int calculate_outputm25(int input___0);
int calculate_outputm26(int input___0);
int a65 = 182;
int a46 = 7;
int a107 = 2;
int a110 = 2;
int a22 = 10;
int a13 = 36;
int a140 = 34;
int a58 = 3;
int cf = 1;
int a42 = 14;
int errorCheck(void) {

  { return (0); }
}
int calculate_outputm1(int input___0) {

  {
    if (cf == 1) {
      if (input___0 == 4) {
        if (a140 == 33) {
          if (a58 == 1) {
            if (a65 <= 117) {
              cf = 0;
              a22 = a46 + 12;
              a46 = a58 + 5;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm2(int input___0) {

  {
    if (a65 <= 117) {
      if (a140 == 33) {
        if (cf == 1) {
          if (input___0 == 6) {
            if (a58 == 1) {
              cf = 0;
              a42 = a110 - -1;
              a65 = ((a65 % 28 + 170) * 5) % 28 + 156;
              a140 = 34;
              a58 = a110 * a42 + -53;
              a46 = a110 - 2;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm3(int input___0) {

  {
    if (140 < a65) {
      if (198 >= a65) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (cf == 1) {
              if (input___0 == 5) {
                cf = 0;
                a46 = a58 + 1;
                a65 = (((a65 - -19257) + -43467) + -5014) % 11 + 130;
                a42 = (a46 - a58) + 12;
                a140 = 32;
                a58 = a46 + -2;
              }
            }
          }
        }
      }
    }
    if (cf == 1) {
      if (input___0 == 3) {
        if (140 < a65) {
          if (198 >= a65) {
            if (a140 == 34) {
              if (a58 == 3) {
                cf = 0;
                a42 = a46 + 9;
                a46 = (a42 - a42) + 5;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm4(int input___0) {

  {
    if (a140 == 34) {
      if (a58 == 3) {
        if (140 < a65) {
          if (198 >= a65) {
            if (input___0 == 1) {
              if (cf == 1) {
                cf = 0;
                a107 = a46 + 2;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm5(int input___0) {

  {
    if (a58 == 3) {
      if (input___0 == 6) {
        if (cf == 1) {
          if (140 < a65) {
            if (198 >= a65) {
              if (a140 == 34) {
                cf = 0;
                a65 = ((a65 % 11 + 124) - -16783) + -16785;
                a140 = 32;
                a42 = a107 + 7;
                a46 = a58 * a58 + -5;
                a58 = a107 - 1;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm6(int input___0) {

  {
    if (cf == 1) {
      if (input___0 == 2) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
                a46 = a107 / a107 + 6;
                a42 = a46 + 1;
              }
            }
          }
        }
      }
    }
    if (input___0 == 5) {
      if (cf == 1) {
        if (a140 == 34) {
          if (a58 == 3) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
                a22 = a46 + 6;
                a46 = a58 - -3;
                a65 = (a65 / 5) / 5 - 27340;
                a140 = 33;
                a58 = a22 + -8;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm7(int input___0) {

  {
    if (140 < a65) {
      if (198 >= a65) {
        if (a58 == 3) {
          if (input___0 == 6) {
            if (cf == 1) {
              if (a140 == 34) {
                cf = 0;
                a107 = (a46 - a58) + 1;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm8(int input___0) {

  {
    if (a58 == 2) {
      if (117 < a65) {
        if (140 >= a65) {
          if (cf == 1) {
            if (input___0 == 3) {
              if (a140 == 32) {
                cf = 0;
                a46 = a42 - 5;
                a107 = a58;
                a140 = 34;
                a65 = (((a65 - 15309) + 15342) * 5) % 28 + 152;
                a58 = (a46 + a107) - 2;
              }
            }
          }
        }
      }
    }
    if (cf == 1) {
      if (input___0 == 7) {
        if (a58 == 2) {
          if (117 < a65) {
            if (140 >= a65) {
              if (a140 == 32) {
                cf = 0;
                a140 = 34;
                a65 = ((a65 + 17501) - -1347) + -18815;
                a58 = a46 / a46 - -2;
                a46 = a42 + -5;
                a107 = a42 + -7;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm9(int input___0) {

  {
    if (a140 == 32) {
      if (117 < a65) {
        if (140 >= a65) {
          if (a58 == 2) {
            if (input___0 == 6) {
              if (cf == 1) {
                cf = 0;
                a65 = ((a65 - 19945) - 7150) / 5;
                a110 = a46 * a42 + -34;
                a140 = 33;
                a46 = a58 - 1;
                a58 = 1;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm10(int input___0) {

  {
    if (117 < a65) {
      if (140 >= a65) {
        if (input___0 == 5) {
          if (cf == 1) {
            if (a140 == 32) {
              if (a58 == 2) {
                cf = 0;
                a65 = ((a65 / -5) * 5) * 5;
                a140 = 33;
                a46 = a42 + -4;
                a13 = 34;
                a58 = a42 / a46;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm11(int input___0) {

  {
    if (a140 == 32) {
      if (input___0 == 1) {
        if (cf == 1) {
          if (a58 == 2) {
            if (117 < a65) {
              if (140 >= a65) {
                cf = 0;
                a42 = a46 / a58 + 10;
                a65 = ((a65 - -2087) + -2057) + 23;
                a58 = a42 / a46;
                a140 = 34;
                a46 = (a42 - a42) + 5;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm12(int input___0) {

  {
    if (a58 == 2) {
      if (cf == 1) {
        if (input___0 == 7) {
          if (a140 == 32) {
            if (117 < a65) {
              if (140 >= a65) {
                cf = 0;
                a65 = ((a65 + -21407) - -21457) + 6;
                a46 = a58 + 3;
                a42 = a58 * a46 + 1;
                a140 = 34;
                a58 = a46 + -2;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm13(int input___0) {

  {
    if (input___0 == 4) {
      if (cf == 1) {
        if (a58 == 3) {
          if (140 < a65) {
            if (198 >= a65) {
              if (a140 == 34) {
                cf = 0;
                a65 = (((a65 % 11 + 118) - 8968) - 4912) + 13885;
                a42 = a58 + 11;
                a46 = a58 / a58 - -3;
                a140 = 32;
                a58 = 2;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm14(int input___0) {

  {
    if (a140 == 34) {
      if (a58 == 3) {
        if (140 < a65) {
          if (198 >= a65) {
            if (cf == 1) {
              if (input___0 == 9) {
                cf = 0;
                a107 = a42 - 4;
                a46 = a107 + -2;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm15(int input___0) {

  {
    if (140 < a65) {
      if (198 >= a65) {
        if (a140 == 34) {
          if (input___0 == 3) {
            if (cf == 1) {
              if (a58 == 3) {
                cf = 0;
                a13 = 36;
                a65 = (a65 * -5 - 1540) * 5;
                a46 = a42 - 3;
                a140 = 33;
                a58 = a42 / a46;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm16(int input___0) {

  {
    if (a58 == 3) {
      if (cf == 1) {
        if (input___0 == 8) {
          if (a140 == 34) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
                a107 = a46 + -4;
                a46 = a58;
              }
            }
          }
        }
      }
    }
    if (140 < a65) {
      if (198 >= a65) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (cf == 1) {
              if (input___0 == 6) {
                cf = 0;
                a140 = 32;
                a65 = ((a65 % 11 + 123) - -3) + 4;
                a46 = a58 + 1;
                a42 = a58 - -5;
                a58 = a46 - 2;
              }
            }
          }
        }
      }
    }
    if (a140 == 34) {
      if (140 < a65) {
        if (198 >= a65) {
          if (a58 == 3) {
            if (input___0 == 2) {
              if (cf == 1) {
                cf = 0;
                a107 = (a46 + a58) + -7;
                a46 = a42 / a107 - 9;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm17(int input___0) {

  {
    if (a65 <= 117) {
      if (cf == 1) {
        if (input___0 == 4) {
          if (a140 == 33) {
            if (a58 == 1) {
              cf = 0;
              a22 = a58 / a58 + 9;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm18(int input___0) {

  {
    if (input___0 == 2) {
      if (cf == 1) {
        if (a140 == 33) {
          if (a65 <= 117) {
            if (a58 == 1) {
              cf = 0;
              a65 = (a65 / 5 + -11387) % 28 - -182;
              a140 = 34;
              a46 = a58 - -2;
              a107 = a58 - -4;
              a58 = (a107 - a22) - -7;
            }
          }
        }
      }
    }
    if (a140 == 33) {
      if (cf == 1) {
        if (input___0 == 9) {
          if (a58 == 1) {
            if (a65 <= 117) {
              cf = 0;
              a140 = 34;
              a42 = a22 - 2;
              a65 = (((a65 % 28 + 170) + -1) + 18473) - 18471;
              a46 = a42;
              a58 = (a22 - a42) + 1;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm19(int input___0) {

  {
    if (input___0 == 4) {
      if (cf == 1) {
        if (a140 == 33) {
          if (a65 <= 117) {
            if (a58 == 1) {
              cf = 0;
              a46 = a22 - 9;
              a110 = a22 / a46 + -3;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm20(int input___0) {

  {
    if (a140 == 33) {
      if (a65 <= 117) {
        if (a58 == 1) {
          if (input___0 == 5) {
            if (cf == 1) {
              cf = 0;
              a22 = a46 + 4;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm21(int input___0) {

  {
    if (a140 == 34) {
      if (cf == 1) {
        if (input___0 == 5) {
          if (140 < a65) {
            if (198 >= a65) {
              if (a58 == 3) {
                cf = 0;
              }
            }
          }
        }
      }
    }
    if (a140 == 34) {
      if (cf == 1) {
        if (input___0 == 9) {
          if (a58 == 3) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
              }
            }
          }
        }
      }
    }
    if (a140 == 34) {
      if (input___0 == 6) {
        if (cf == 1) {
          if (a58 == 3) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
                a42 = a46 / a46 + 8;
                a46 = a58 - -2;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm22(int input___0) {

  {
    if (140 < a65) {
      if (198 >= a65) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (cf == 1) {
              if (input___0 == 9) {
                cf = 0;
              }
            }
          }
        }
      }
    }
    if (cf == 1) {
      if (input___0 == 1) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
                a46 = a58;
                a107 = a58 - 1;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm23(int input___0) {

  {
    if (a58 == 3) {
      if (140 < a65) {
        if (198 >= a65) {
          if (a140 == 34) {
            if (cf == 1) {
              if (input___0 == 8) {
                cf = 0;
                a46 = a58 / a58 + 5;
                a58 = a42 / a46 - 1;
                a140 = 33;
                a65 = (a65 * 5 - 12940) * 2;
                a22 = a46 - -2;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm24(int input___0) {

  {
    if (cf == 1) {
      if (input___0 == 7) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
                a46 = a58 + 2;
                a42 = a46 + 4;
              }
            }
          }
        }
      }
    }
    if (a58 == 3) {
      if (input___0 == 5) {
        if (cf == 1) {
          if (a140 == 34) {
            if (140 < a65) {
              if (198 >= a65) {
                cf = 0;
                a42 = (a46 + a46) - 2;
              }
            }
          }
        }
      }
    }
    if (a58 == 3) {
      if (input___0 == 9) {
        if (cf == 1) {
          if (140 < a65) {
            if (198 >= a65) {
              if (a140 == 34) {
                cf = 0;
                a107 = a58 + 4;
                a46 = a42 - 11;
              }
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm25(int input___0) {

  {
    if (a140 == 33) {
      if (a65 <= 117) {
        if (cf == 1) {
          if (input___0 == 2) {
            if (a58 == 1) {
              cf = 0;
              a140 = 34;
              a46 = a58 * a58 - -2;
              a65 = (((a65 % 28 - -168) / 5) * 51) / 10;
              a107 = a58 + 2;
              a58 = (a107 - a107) + 3;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_outputm26(int input___0) {

  {
    if (a58 == 1) {
      if (a140 == 33) {
        if (cf == 1) {
          if (input___0 == 3) {
            if (a65 <= 117) {
              cf = 0;
              a140 = 32;
              a46 = a58 + 3;
              a42 = (a58 - a46) - -15;
              a65 = ((a65 % 11 - -129) - -1917) - 1916;
              a58 = a42 + -10;
            }
          }
        }
      }
    }
    return (0);
  }
}
int calculate_output(int input___0) {

  {
    cf = 1;
    if (a140 == 33) {
      if (a58 == 1) {
        if (cf == 1) {
          if (a46 == 1) {
            if (a65 <= 117) {
              if (a140 == 33) {
                if (a58 == 1) {
                  if (a110 == 6) {
                    if (cf == 1) {
                      if (a65 <= 117) {
                        calculate_outputm1(input___0);
                      }
                    }
                  }
                }
              }
              if (a140 == 33) {
                if (a58 == 1) {
                  if (a65 <= 117) {
                    if (cf == 1) {
                      if (a110 == 7) {
                        calculate_outputm2(input___0);
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (a140 == 34) {
      if (140 < a65) {
        if (198 >= a65) {
          if (cf == 1) {
            if (a46 == 3) {
              if (a58 == 3) {
                if (140 < a65) {
                  if (198 >= a65) {
                    if (a107 == 1) {
                      if (cf == 1) {
                        if (a58 == 3) {
                          if (a140 == 34) {
                            calculate_outputm3(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (cf == 1) {
                  if (a107 == 2) {
                    if (a140 == 34) {
                      if (140 < a65) {
                        if (198 >= a65) {
                          if (a58 == 3) {
                            calculate_outputm4(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a58 == 3) {
                  if (a140 == 34) {
                    if (140 < a65) {
                      if (198 >= a65) {
                        if (cf == 1) {
                          if (a107 == 3) {
                            calculate_outputm5(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a107 == 5) {
                  if (cf == 1) {
                    if (a58 == 3) {
                      if (140 < a65) {
                        if (198 >= a65) {
                          if (a140 == 34) {
                            calculate_outputm6(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a58 == 3) {
                  if (140 < a65) {
                    if (198 >= a65) {
                      if (a107 == 7) {
                        if (cf == 1) {
                          if (a140 == 34) {
                            calculate_outputm7(input___0);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (a58 == 2) {
      if (a46 == 4) {
        if (cf == 1) {
          if (117 < a65) {
            if (140 >= a65) {
              if (a140 == 32) {
                if (117 < a65) {
                  if (140 >= a65) {
                    if (a58 == 2) {
                      if (a42 == 8) {
                        if (cf == 1) {
                          if (a140 == 32) {
                            calculate_outputm8(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a42 == 10) {
                  if (cf == 1) {
                    if (a140 == 32) {
                      if (117 < a65) {
                        if (140 >= a65) {
                          if (a58 == 2) {
                            calculate_outputm9(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a140 == 32) {
                  if (117 < a65) {
                    if (140 >= a65) {
                      if (a58 == 2) {
                        if (a42 == 12) {
                          if (cf == 1) {
                            calculate_outputm10(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a58 == 2) {
                  if (cf == 1) {
                    if (a42 == 13) {
                      if (a140 == 32) {
                        if (117 < a65) {
                          if (140 >= a65) {
                            calculate_outputm11(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (117 < a65) {
                  if (140 >= a65) {
                    if (a140 == 32) {
                      if (a58 == 2) {
                        if (cf == 1) {
                          if (a42 == 14) {
                            calculate_outputm12(input___0);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (140 < a65) {
      if (198 >= a65) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (a46 == 5) {
              if (cf == 1) {
                if (a140 == 34) {
                  if (a58 == 3) {
                    if (140 < a65) {
                      if (198 >= a65) {
                        if (cf == 1) {
                          if (a42 == 8) {
                            calculate_outputm13(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a140 == 34) {
                  if (a42 == 9) {
                    if (cf == 1) {
                      if (140 < a65) {
                        if (198 >= a65) {
                          if (a58 == 3) {
                            calculate_outputm14(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a42 == 11) {
                  if (cf == 1) {
                    if (140 < a65) {
                      if (198 >= a65) {
                        if (a140 == 34) {
                          if (a58 == 3) {
                            calculate_outputm15(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a140 == 34) {
                  if (a42 == 12) {
                    if (cf == 1) {
                      if (a58 == 3) {
                        if (140 < a65) {
                          if (198 >= a65) {
                            calculate_outputm16(input___0);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (a58 == 1) {
      if (a65 <= 117) {
        if (a140 == 33) {
          if (a46 == 6) {
            if (cf == 1) {
              if (a140 == 33) {
                if (a58 == 1) {
                  if (cf == 1) {
                    if (a22 == 8) {
                      if (a65 <= 117) {
                        calculate_outputm17(input___0);
                      }
                    }
                  }
                }
              }
              if (a65 <= 117) {
                if (a58 == 1) {
                  if (a140 == 33) {
                    if (cf == 1) {
                      if (a22 == 9) {
                        calculate_outputm18(input___0);
                      }
                    }
                  }
                }
              }
              if (a22 == 10) {
                if (cf == 1) {
                  if (a140 == 33) {
                    if (a65 <= 117) {
                      if (a58 == 1) {
                        calculate_outputm19(input___0);
                      }
                    }
                  }
                }
              }
              if (a65 <= 117) {
                if (a140 == 33) {
                  if (a22 == 13) {
                    if (cf == 1) {
                      if (a58 == 1) {
                        calculate_outputm20(input___0);
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (cf == 1) {
      if (a46 == 7) {
        if (a58 == 3) {
          if (a140 == 34) {
            if (140 < a65) {
              if (198 >= a65) {
                if (a42 == 7) {
                  if (cf == 1) {
                    if (a140 == 34) {
                      if (a58 == 3) {
                        if (140 < a65) {
                          if (198 >= a65) {
                            calculate_outputm21(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (140 < a65) {
                  if (198 >= a65) {
                    if (a58 == 3) {
                      if (a140 == 34) {
                        if (cf == 1) {
                          if (a42 == 8) {
                            calculate_outputm22(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (140 < a65) {
                  if (198 >= a65) {
                    if (a140 == 34) {
                      if (a58 == 3) {
                        if (cf == 1) {
                          if (a42 == 12) {
                            calculate_outputm23(input___0);
                          }
                        }
                      }
                    }
                  }
                }
                if (a58 == 3) {
                  if (a42 == 14) {
                    if (cf == 1) {
                      if (140 < a65) {
                        if (198 >= a65) {
                          if (a140 == 34) {
                            calculate_outputm24(input___0);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (a65 <= 117) {
      if (a140 == 33) {
        if (a58 == 1) {
          if (cf == 1) {
            if (a46 == 8) {
              if (a58 == 1) {
                if (a140 == 33) {
                  if (a65 <= 117) {
                    if (cf == 1) {
                      if (a13 == 34) {
                        calculate_outputm25(input___0);
                      }
                    }
                  }
                }
              }
              if (a58 == 1) {
                if (a140 == 33) {
                  if (a65 <= 117) {
                    if (a13 == 36) {
                      if (cf == 1) {
                        calculate_outputm26(input___0);
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    errorCheck();
    if (cf == 1) {
    }
    return (0);
  }
}

int main() {
  int *symb;
  unsigned int __lengthofsymb;
  void *tmp;
  int FLAG;

  {
    __lengthofsymb = (unsigned int)BOUND;
    tmp = __builtin_alloca(sizeof(*symb) * __lengthofsymb);
    symb = (int *)tmp;
    klee_make_symbolic(symb, sizeof(int) * (unsigned int)BOUND, "symb");
    FLAG = 0;
    while (FLAG < BOUND) {
      if (*(symb + FLAG) != 5) {
        if (*(symb + FLAG) != 6) {
          if (*(symb + FLAG) != 1) {
            if (*(symb + FLAG) != 7) {
              if (*(symb + FLAG) != 2) {
                if (*(symb + FLAG) != 8) {
                  if (*(symb + FLAG) != 3) {
                    if (*(symb + FLAG) != 9) {
                      if (*(symb + FLAG) != 10) {
                        if (*(symb + FLAG) != 4) {
                          return (-2);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      calculate_output(*(symb + FLAG));
      FLAG = FLAG + 1;
    }
    /*  _SLICE(kappa);*/
    return (0);
  }
}
