# Makefile environment settings file
#
# Copyright 2015 National University of Singapore

CC=clang
KLEE=${HOME}/git/memdepend/klee/Release+Asserts/bin/klee
AS=${CC} -S -emit-llvm
CFLAGS=-emit-llvm -g -I${HOME}/nus/kleetest
KLEE_FLAGS=-write-pcs -use-query-log=all:pc,all:smt2 -search=dfs

