/* Obtained from http://www.mrtc.mdh.se/projects/wcet/benchmarks.html,
 * with KLEE harnessing added */

/* $Id: nsichneu.c,v 1.3 2005/04/15 09:18:42 jgn Exp $ */

/***************************************************************************
*
* Copyright (c) 1998/1999, C-LAB, Paderborn
*
* File generated by Sea2CHaRy
*
* This file containes a CHaRy description generated from the
* file: NSicherNeu.sea
* The name of the Pr/T-Net was: NSicherNeu
*
* Modified and maintained by
* Friedhelm Stappert
* C-LAB, Paderborn, Germany
* fst@c-lab.de
*
* Modifications:
* o made the local variables global and volatile,
*   so the compiler won't optimise everything away.
*

***************************************************************************/
// #define DO_TRACING
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif

#ifdef DO_TRACING   // ON PC

#include <stdio.h>
#define TRACE(x) trace((x))
#undef TEST                   /* finished testing! */
void trace(char *s)
{
   printf("%s\n",s);
}

#else               // ON TARGET

#define TRACE(x)
#undef TEST

#endif



/* volatile */ int	P1_is_marked = 3;
/* volatile */ long	P1_marking_member_0[3];
/* volatile */ int	P2_is_marked = 5;
/* volatile */ long	P2_marking_member_0[5];
/* volatile */ int	P3_is_marked = 0;
/* volatile */ long	P3_marking_member_0[6];



/**void NSicherNeu()**/
int main()
{
  char s[100];
  char *p=s;
   int dummy_i;
/*   dummy_i = 17; Takes too much time */
   dummy_i = 2;

#ifdef LLBMC
  P1_marking_member_0[0] = __llbmc_nondef_long();
  P1_marking_member_0[1] = __llbmc_nondef_long();
  P1_marking_member_0[2] = __llbmc_nondef_long();
  P1_is_marked = __llbmc_nondef_int();

  P2_marking_member_0[0] = __llbmc_nondef_long();
  P2_marking_member_0[1] = __llbmc_nondef_long();
  P2_marking_member_0[2] = __llbmc_nondef_long();
  P2_marking_member_0[3] = __llbmc_nondef_long();
  P2_marking_member_0[4] = __llbmc_nondef_long();
  P2_is_marked = __llbmc_nondef_int();

  P3_marking_member_0[0] = __llbmc_nondef_long();
  P3_marking_member_0[1] = __llbmc_nondef_long();
  P3_marking_member_0[2] = __llbmc_nondef_long();
  P3_marking_member_0[3] = __llbmc_nondef_long();
  P3_marking_member_0[4] = __llbmc_nondef_long();
  P3_marking_member_0[5] = __llbmc_nondef_long();
  P3_is_marked = __llbmc_nondef_int();
#else
   klee_make_symbolic(P1_marking_member_0, 3 * sizeof(long), "P1_marking_member_0");
   klee_make_symbolic(&P1_is_marked, sizeof(int), "P1_is_marked");
   klee_make_symbolic(P2_marking_member_0, 5 * sizeof(long), "P2_marking_member_0");
   klee_make_symbolic(&P2_is_marked, sizeof(int), "P2_is_marked");
   klee_make_symbolic(P3_marking_member_0, 6 * sizeof(long), "P3_marking_member_0");
   klee_make_symbolic(&P3_is_marked, sizeof(int), "P3_is_marked");
#endif

//   while (dummy_i > 0) {

      dummy_i--;
      p += 1;
      /* Permutation for Place P1 : 0, 1, 2 */
      /* Transition T1 */
      if ( (P1_is_marked >= 3) ){ //&&
//           (P3_is_marked + 3 <= 6) &&
//           (P1_marking_member_0[1] == P1_marking_member_0[2]) ) {

         long	x;
         long	y;
         long	z;
	 p += 2;
         x = P1_marking_member_0[0];
         y = P1_marking_member_0[1];
         p += 2;
         /* Transition condition */
         if (x < y) {

				/* demarking of input places */
            P1_is_marked -= 3;

				/* preaction */
            z = x - y;

				/* marking of output places */
            P3_marking_member_0[P3_is_marked+0] = x;
            P3_marking_member_0[P3_is_marked+1] = y;
            P3_marking_member_0[P3_is_marked+2] = z;
            P3_is_marked += 3;
	    p += 6;
         } /* end of if (Transition condition) */
      }

//      /* Permutation for Place P1 : 0, 2, 1 */
//      /* Transition T1 */
//      if ( (P1_is_marked >= 3) &&
//           (P3_is_marked + 3 <= 6) &&
//           (P1_marking_member_0[2] == P1_marking_member_0[1]) ) {
//
//         long	x;
//         long	y;
//         long	z;
//
//         x = P1_marking_member_0[0];
//         y = P1_marking_member_0[2];
//	 p += 2;
//         /* Transition condition */
//         if ((x < y)) {
//
//
//				/* demarking of input places */
//            P1_is_marked -= 3;
//
//				/* preaction */
//            z = x - y;
//
//				/* marking of output places */
//            P3_marking_member_0[P3_is_marked+0] = x;
//            P3_marking_member_0[P3_is_marked+1] = y;
//            P3_marking_member_0[P3_is_marked+2] = z;
//            P3_is_marked += 3;
//	    p += 6;
//         } /* end of if (Transition condition) */
//      }
//
//      /* Permutation for Place P1 : 1, 0, 2 */
//      /* Transition T1 */
//      if ( (P1_is_marked >= 3) &&
//           (P3_is_marked + 3 <= 6) &&
//           (P1_marking_member_0[0] == P1_marking_member_0[2]) ) {
//
//         long	x;
//         long	y;
//         long	z;
//
//         x = P1_marking_member_0[1];
//         y = P1_marking_member_0[0];
//         p += 2;
//         /* Transition condition */
//         if (x < y) {
//
//
//				/* demarking of input places */
//            P1_is_marked -= 3;
//
//				/* preaction */
//            z = x - y;
//
//				/* marking of output places */
//            P3_marking_member_0[P3_is_marked+0] = x;
//            P3_marking_member_0[P3_is_marked+1] = y;
//            P3_marking_member_0[P3_is_marked+2] = z;
//            P3_is_marked += 3;
//            p += 6;
//         } /* end of if (Transition condition) */
//      }
//
//      /* Permutation for Place P1 : 1, 2, 0 */
//      /* Transition T1 */
//      if ( (P1_is_marked >= 3) &&
//           (P3_is_marked + 3 <= 6) &&
//           (P1_marking_member_0[2] == P1_marking_member_0[0])) {
//
//         long	x;
//         long	y;
//         long	z;
//
//         x = P1_marking_member_0[1];
//         y = P1_marking_member_0[2];
//         p += 2;
//         /* Transition condition */
//         if ((x < y)) {
//
//
//				/* demarking of input places */
//            P1_is_marked -= 3;
//
//				/* preaction */
//            z = x - y;
//
//				/* marking of output places */
//            P3_marking_member_0[P3_is_marked+0] = x;
//            P3_marking_member_0[P3_is_marked+1] = y;
//            P3_marking_member_0[P3_is_marked+2] = z;
//            P3_is_marked += 3;
//            p += 6;
//         } /* end of if (Transition condition) */
//      }
//   }


   dummy_i = 77;

   return *p;


}

/***************************************************************************
 *
 * end of file
 *
 ***************************************************************************/

