# Makefile to build and run the examples using KLEE.
#
# Copyright 2015 National University of Singapore

TARGETS=addition.klee \
	arraysimple2.klee \
	even.klee \
	polynomial.klee \
	addition_safe.klee \
	interproc.klee \
	addition_depend.klee \
	addition_safe_small.klee \
	sp.klee

include ../Makefile.common

