# Makefile to build and run the examples using KLEE.
#
# Copyright 2015 National University of Singapore

TARGETS=double-free.klee memory-access.klee openssl.klee polynomial.klee popcount.klee

include ../Makefile.common

